### ISSUE TITLE
Too much memory is used

### ISSUE THREAD

**Issue by Kirez** [Kirez/dat055g1#7]

**Comment by Kirez** [comment]
Looks like this might be solved by the last few commits. We no longer have crashes from using to much memory. Could be that closing the window now stops the process. In old version this was not the case so when debugging you would have 10+ lost processes eating memory.

**Comment by linusberglund** [comment]
Confirmed, the process never used more than 280 MB (idling at 140) on my local computer as of commit db2b94e4ccdc28bd6d4799e137a97a4e160866dc
