### ISSUE TITLE
Current revision (c46e82) crashes on startup

### ISSUE THREAD

**Issue by linusberglund** [Kirez/dat055g1#9]
# Reproduce
Build & run the game
# Reproduction rate
10/10

# System info
* Windows 10 64-bit
* Intel Core i7 4770K
* nVidia GeForce GTX 970 SLI
* BenQ XL2411T (144 Hz)

# IDE
IntelliJ IDEA 2016.3.3
Build #IC-163.11103.6, built on January 16, 2017
JRE: 1.8.0_112-release-408-b6 x86
JVM: OpenJDK Server VM by JetBrains s.r.o

# Screenshot
![2017-02-19 11_10_27-timmyfightgogo not responding](https://cloud.githubusercontent.com/assets/14021896/23101464/13bdfa0c-f694-11e6-8fa9-93117ce67a7c.png)

**Comment by linusberglund** [comment]
**Addendum**
My fork (as of the revision [edfaac8](https://github.com/Zombax/dat055g1/commit/edfaac8fb7ed39ea06fd67b21c005c817a176772)) works

**Comment by Kirez** [comment]
Confirmed. Must have committed early or something. However this is now fixed from 
9f07d55f5e196c97236ac765399aa35e00c5bc71 and later
